## Dataset Note
This project uses IPL data (2008-2026) from Kaggle. The 2026 season data may be partial/incomplete as it was likely captured before the season's final matches were played, so 2026 statistics (e.g., Orange Cap standings) may not match the actual final season results.

In [21]:
print(matches.shape) # how much rows and columns
print(matches.columns) #matches.column

(1212, 23)
Index(['match_id', 'season_id', 'balls_per_over', 'city', 'match_date',
       'event_name', 'match_number', 'gender', 'match_type', 'format', 'overs',
       'season', 'team_type', 'venue', 'toss_winner', 'team1', 'team2',
       'toss_decision', 'match_winner', 'win_by_runs', 'win_by_wickets',
       'result', 'player_of_match'],
      dtype='object')

In [24]:
print(matches.head(3))
print(matches.tail(3))

   match_id  season_id  balls_per_over       city  match_date  \
0    335982       2008               6  Bangalore  2008-04-18
1   1082591       2017               6  Hyderabad  2017-04-05
2   1082592       2017               6       Pune  2017-04-06

              event_name  match_number gender match_type format  ...  \
0  Indian Premier League           1.0   male        T20    T20  ...
1  Indian Premier League           1.0   male        T20    T20  ...
2  Indian Premier League           2.0   male        T20    T20  ...

                                       venue toss_winner team1 team2  \
0                      M Chinnaswamy Stadium           1     1     6
1  Rajiv Gandhi International Stadium, Uppal           1     2     1
2    Maharashtra Cricket Association Stadium           4     4     3

   toss_decision  match_winner  win_by_runs win_by_wickets  result  \
0          field             6        140.0            NaN     win
1          field             2         35.0            NaN     win
2          field             4          NaN            7.0     win

   player_of_match
0             46.0
1             15.0
2             36.0

[3 rows x 23 columns]
      match_id  season_id  balls_per_over       city  match_date  \
1209   1529284       2026               6     Mumbai  2026-04-29
1210   1529285       2026               6  Ahmedabad  2026-04-30
1211   1529286       2026               6     Jaipur  2026-05-01

                 event_name  match_number gender match_type format  ...  \
1209  Indian Premier League          41.0   male        T20    T20  ...
1210  Indian Premier League          42.0   male        T20    T20  ...
1211  Indian Premier League          43.0   male        T20    T20  ...

                                 venue toss_winner team1 team2  toss_decision  \
1209          Wankhede Stadium, Mumbai           3     3     2            bat
1210  Narendra Modi Stadium, Ahmedabad         615     1   615          field
1211    Sawai Mansingh Stadium, Jaipur         134   134   252            bat

      match_winner  win_by_runs win_by_wickets  result  player_of_match
1209             2          NaN            6.0     win           1740.0
1210           615          NaN            4.0     win           4098.0
1211           252          NaN            7.0     win           1409.0

[3 rows x 23 columns]

In [25]:
# Data Cleaning 
# step 1
print(matches.isnull().sum())  #it will show in columns  missing/empty values how much

match_id             0
season_id            0
balls_per_over       0
city                51
match_date           0
event_name           0
match_number        70
gender               0
match_type           0
format               0
overs                0
season               0
team_type            0
venue                0
toss_winner          0
team1                0
team2                0
toss_decision        0
match_winner         0
win_by_runs        666
win_by_wickets     571
result               0
player_of_match      9
dtype: int64

In [4]:
# clean missing/empty in columns

matches = matches.fillna({
    "city":"Unknown",
    "match_number":"Unknown",
    "win_by_runs":0,
    "win_by_wickets":0,
    "player_of_match":" No Result"
    })

In [5]:
# now not missing/empty check bellow
print(matches.isnull().sum())

match_id           0
season_id          0
balls_per_over     0
city               0
match_date         0
event_name         0
match_number       0
gender             0
match_type         0
format             0
overs              0
season             0
team_type          0
venue              0
toss_winner        0
team1              0
team2              0
toss_decision      0
match_winner       0
win_by_runs        0
win_by_wickets     0
result             0
player_of_match    0
dtype: int64

In [6]:
# checking Duplicates values 
print(matches.duplicated().sum())

0

In [7]:
# but don't have dupicates values
# suppose u have duplicates values use bellow fuction
matches = matches.drop_duplicates()
# tahn use shape funtion to check reomve or not
print(matches.shape)

(1212, 23)

In [8]:
print(matches.dtypes)

match_id             int64
season_id            int64
balls_per_over       int64
city                object
match_date          object
event_name          object
match_number        object
gender              object
match_type          object
format              object
overs                int64
season               int64
team_type           object
venue               object
toss_winner          int64
team1                int64
team2                int64
toss_decision       object
match_winner         int64
win_by_runs        float64
win_by_wickets     float64
result              object
player_of_match     object
dtype: object

In [9]:
# convert match_date column into date bcz now not in date
matches["match_date"] = pd.to_datetime(matches["match_date"])
print(matches.dtypes)

match_id                    int64
season_id                   int64
balls_per_over              int64
city                       object
match_date         datetime64[ns]
event_name                 object
match_number               object
gender                     object
match_type                 object
format                     object
overs                       int64
season                      int64
team_type                  object
venue                      object
toss_winner                 int64
team1                       int64
team2                       int64
toss_decision              object
match_winner                int64
win_by_runs               float64
win_by_wickets            float64
result                     object
player_of_match            object
dtype: object

In [10]:
# we can be see which types data stored in column 
print(matches['season'].unique())

[2008 2017 2018 2019 2020 2021 2022 2023 2024 2025 2009 2010 2011 2012
 2013 2014 2015 2016 2026]

In [11]:
# use replace functions 
matches["season"] = matches["season"].replace("2020/21","2020")

In [12]:
# convert season column into int

matches["season"] = matches["season"].astype(int)

In [34]:
print(matches["season"].unique())

[2008 2017 2018 2019 2020 2021 2022 2023 2024 2025 2009 2010 2011 2012
 2013 2014 2015 2016 2026]

In [13]:
print(matches['city'].unique())

['Bangalore' 'Hyderabad' 'Pune' 'Rajkot' 'Indore' 'Bengaluru' 'Mumbai'
 'Kolkata' 'Delhi' 'Chandigarh' 'Kanpur' 'Chennai' 'Jaipur'
 'Visakhapatnam' 'Abu Dhabi' 'Unnkown' 'Ahmedabad' 'Sharjah' 'Dubai'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Dharamsala' 'Mohali' 'Cape Town'
 'Port Elizabeth' 'Durban' 'Centurion' 'East London' 'Johannesburg'
 'Kimberley' 'Bloemfontein' 'Cuttack' 'Nagpur' 'Kochi' 'Raipur' 'Ranchi'
 'New Chandigarh']

In [14]:
# text columns ka extra space automatically remove karta hai 

text_columns = matches.select_dtypes(include='object').columns
for col in text_columns:
    matches[col] = matches[col].str.strip()

In [39]:
print(matches['city'].unique())

['Bangalore' 'Hyderabad' 'Pune' 'Rajkot' 'Indore' 'Bengaluru' 'Mumbai'
 'Kolkata' 'Delhi' 'Chandigarh' 'Kanpur' 'Chennai' 'Jaipur'
 'Visakhapatnam' 'Abu Dhabi' 'Unnkown' 'Ahmedabad' 'Sharjah' 'Dubai'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Dharamsala' 'Mohali' 'Cape Town'
 'Port Elizabeth' 'Durban' 'Centurion' 'East London' 'Johannesburg'
 'Kimberley' 'Bloemfontein' 'Cuttack' 'Nagpur' 'Kochi' 'Raipur' 'Ranchi'
 'New Chandigarh']

In [15]:
# for Save Data clean

matches.to_csv("matches_clean.csv", index = False)
print("saved")

saved

In [5]:
# 2nd file cleaning 


deliveries = pd.read_csv('ball_by_ball_data.csv')
deliveries

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,252,134,18,3,1,...,False,False,0,0,0,0,0,NaN,False,2
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,252,134,18,4,1,...,False,False,0,0,0,0,0,NaN,False,2
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,252,134,18,5,4,...,False,False,0,0,0,0,0,NaN,False,2
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,252,134,19,0,4,...,False,False,0,0,0,0,0,NaN,False,2
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,252,134,19,1,0,...,False,False,0,1,0,0,0,NaN,False,2

In [6]:
print(deliveries.shape)
print(deliveries.columns)

(288226, 30)
Index(['season_id', 'match_id', 'batter', 'bowler', 'non_striker',
       'team_batting', 'team_bowling', 'over_number', 'ball_number',
       'batter_runs', 'extras', 'total_runs', 'batsman_type', 'bowler_type',
       'player_out', 'fielders_involved', 'is_wicket', 'is_wide_ball',
       'is_no_ball', 'is_leg_bye', 'is_bye', 'is_penalty', 'wide_ball_runs',
       'no_ball_runs', 'leg_bye_runs', 'bye_runs', 'penalty_runs',
       'wicket_kind', 'is_super_over', 'innings'],
      dtype='object')

In [7]:
print(deliveries.head(2))
print(deliveries.tail(2))

   season_id  match_id       batter   bowler  non_striker  team_batting  \
0       2008    335982   SC Ganguly  P Kumar  BB McCullum             6
1       2008    335982  BB McCullum  P Kumar   SC Ganguly             6

   team_bowling  over_number  ball_number  batter_runs  ...  is_bye  \
0             1            0            0            0  ...   False
1             1            0            1            0  ...   False

   is_penalty wide_ball_runs no_ball_runs leg_bye_runs bye_runs  penalty_runs  \
0       False              0            0            1        0             0
1       False              0            0            0        0             0

   wicket_kind  is_super_over  innings
0          NaN          False        1
1          NaN          False        1

[2 rows x 30 columns]
        season_id  match_id           batter          bowler non_striker  \
288224       2026   1529286  Ashutosh Sharma  Brijesh Sharma    T Stubbs
288225       2026   1529286  Ashutosh Sharma  Brijesh Sharma    T Stubbs

        team_batting  team_bowling  over_number  ball_number  batter_runs  \
288224           252           134           19            0            4
288225           252           134           19            1            0

        ...  is_bye  is_penalty wide_ball_runs no_ball_runs leg_bye_runs  \
288224  ...   False       False              0            0            0
288225  ...   False       False              0            1            0

       bye_runs  penalty_runs  wicket_kind  is_super_over  innings
288224        0             0          NaN          False        2
288225        0             0          NaN          False        2

[2 rows x 30 columns]

In [8]:
print(deliveries.dtypes)

season_id             int64
match_id              int64
batter               object
bowler               object
non_striker          object
team_batting          int64
team_bowling          int64
over_number           int64
ball_number           int64
batter_runs           int64
extras                int64
total_runs            int64
batsman_type         object
bowler_type          object
player_out           object
fielders_involved    object
is_wicket              bool
is_wide_ball           bool
is_no_ball             bool
is_leg_bye             bool
is_bye                 bool
is_penalty             bool
wide_ball_runs        int64
no_ball_runs          int64
leg_bye_runs          int64
bye_runs              int64
penalty_runs          int64
wicket_kind          object
is_super_over          bool
innings               int64
dtype: object

In [9]:
# checking missing/empty values

print(deliveries.isnull().sum())

season_id                 0
match_id                  0
batter                    0
bowler                    0
non_striker               0
team_batting              0
team_bowling              0
over_number               0
ball_number               0
batter_runs               0
extras                    0
total_runs                0
batsman_type            239
bowler_type             339
player_out           273886
fielders_involved    273886
is_wicket                 0
is_wide_ball              0
is_no_ball                0
is_leg_bye                0
is_bye                    0
is_penalty                0
wide_ball_runs            0
no_ball_runs              0
leg_bye_runs              0
bye_runs                  0
penalty_runs              0
wicket_kind          273886
is_super_over             0
innings                   0
dtype: int64

In [77]:
#batsman_type            239
#bowler_type             339
#player_out           273886
#fielders_involved    273886
#wicket_kind          273886

In [10]:
# removeing empty/misiing values

deliveries = deliveries.fillna({
    "batsman_type": "Unknown",
    "bowler_type": "Unknown",
    "player_out": "No Wicket",
    "fielders_involved": "Not Applicable",
    "wicket_kind": "No Wicket"
})

In [79]:
print(deliveries.isnull().sum())

season_id            0
match_id             0
batter               0
bowler               0
non_striker          0
team_batting         0
team_bowling         0
over_number          0
ball_number          0
batter_runs          0
extras               0
total_runs           0
batsman_type         0
bowler_type          0
player_out           0
fielders_involved    0
is_wicket            0
is_wide_ball         0
is_no_ball           0
is_leg_bye           0
is_bye               0
is_penalty           0
wide_ball_runs       0
no_ball_runs         0
leg_bye_runs         0
bye_runs             0
penalty_runs         0
wicket_kind          0
is_super_over        0
innings              0
dtype: int64

In [11]:
print(deliveries.duplicated().sum())

0

In [12]:
# now we don't have dupicates values
# suppose u have duplicates values use bellow fuction
deliveries = deliveries.drop_duplicates()
# tahn use shape funtion to check reomve or not
print(deliveries.shape)

(288226, 30)

In [13]:
# clean automatically sapce

text_columns = deliveries.select_dtypes(include='object').columns
for col in text_columns:
    deliveries[col] = deliveries[col].str.strip()

In [15]:
# save file

deliveries.to_csv('deliveries_clean.csv', index=False)
print("Saved")

Saved

In [17]:
print(deliveries.isnull().sum())
print(deliveries.duplicated().sum())
print(deliveries.dtypes)

season_id            0
match_id             0
batter               0
bowler               0
non_striker          0
team_batting         0
team_bowling         0
over_number          0
ball_number          0
batter_runs          0
extras               0
total_runs           0
batsman_type         0
bowler_type          0
player_out           0
fielders_involved    0
is_wicket            0
is_wide_ball         0
is_no_ball           0
is_leg_bye           0
is_bye               0
is_penalty           0
wide_ball_runs       0
no_ball_runs         0
leg_bye_runs         0
bye_runs             0
penalty_runs         0
wicket_kind          0
is_super_over        0
innings              0
dtype: int64
0
season_id             int64
match_id              int64
batter               object
bowler               object
non_striker          object
team_batting          int64
team_bowling          int64
over_number           int64
ball_number           int64
batter_runs           int64
extras                int64
total_runs            int64
batsman_type         object
bowler_type          object
player_out           object
fielders_involved    object
is_wicket              bool
is_wide_ball           bool
is_no_ball             bool
is_leg_bye             bool
is_bye                 bool
is_penalty             bool
wide_ball_runs        int64
no_ball_runs          int64
leg_bye_runs          int64
bye_runs              int64
penalty_runs          int64
wicket_kind          object
is_super_over          bool
innings               int64
dtype: object

In [18]:
# clean file 3 

teams = pd.read_csv('teams_data.csv')
print(teams.shape)
print(teams.isnull().sum())
teams.head()

(16, 2)
team_id      0
team_name    0
dtype: int64

   team_id                    team_name
0        1  Royal Challengers Bangalore
1        2          Sunrisers Hyderabad
2        3               Mumbai Indians
3        4       Rising Pune Supergiant
4        5                Gujarat Lions

In [21]:
print(teams.shape)
print(teams.isnull().sum())
print(teams.columns)
print(teams.dtypes)

(16, 2)
team_id      0
team_name    0
dtype: int64
Index(['team_id', 'team_name'], dtype='object')
team_id       int64
team_name    object
dtype: object

In [22]:
print(teams.duplicated().sum())  # whole files is 100% correct and clean

0

In [23]:
# 4 file

players = pd.read_csv('players-data-updated.csv')

players = players.fillna({
    "bowl_style": "Not a Bowler",
    "field_pos": "Unknown"
})

print(players.isnull().sum())

player_id           0
player_name         0
bat_style           0
bowl_style          0
field_pos           0
player_full_name    0
dtype: int64

In [24]:
players.to_csv('players_clean.csv', index=False)
print("Saved")

Saved

In [2]:
teams = pd.read_csv('teams_data.csv')
team_aliases = pd.read_csv('team_aliases.csv')
players = pd.read_csv('players_clean.csv')

print(teams.shape)
print(team_aliases.shape)
print(players.shape)

(16, 2)
(46, 3)
(799, 6)

In [3]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [5]:
matches = pd.read_csv('matches_clean.csv')
deliveries = pd.read_csv('deliveries_clean.csv')
players = pd.read_csv('players_clean.csv')
teams = pd.read_csv('teams_data.csv')
team_aliases = pd.read_csv('team_aliases.csv')

In [6]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:vansh%401234@localhost/ipl_db')

matches.to_sql('matches', con=engine, if_exists='replace', index=False)
print("Matches done!")

deliveries.to_sql('deliveries', con=engine, if_exists='replace', index=False)
print("Deliveries done!")

players.to_sql('players', con=engine, if_exists='replace', index=False)
print("Players done!")

teams.to_sql('teams', con=engine, if_exists='replace', index=False)
print("Teams done!")

team_aliases.to_sql('team_aliases', con=engine, if_exists='replace', index=False)
print("Team aliases done!")

Matches done!
Deliveries done!
Players done!
Teams done!
Team aliases done!